language: objective-c

osx_image: xcode9
xcode_workspace: ALImageGallery.xcworkspace
xcode_scheme: ALImageGallery

script: set -o pipefail &&  xcodebuild -workspace ALImageGallery.xcworkspace -scheme ALImageGallery -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S Plus' build ;
