language: objective-c

osx_image: xcode7.3
xcode_workspace: ALImageGallery.xcworkspace
xcode_scheme: ALImageGallery

script: set -o pipefail &&  xcodebuild -workspace ALImageGallery.xcworkspace -scheme ALImageGallery -sdk iphonesimulator -destination 'OS=9.2,name=iPhone 6S Plus' build ;
